### PR TITLE
Test branch

### PR DESCRIPTION
**Pull request by sunami09**
```bash
Running main() from /googletest/googletest/src/gtest_main.cc
[==========] Running 30 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 30 tests from GuesserTest
[ RUN      ] GuesserTest.empty_string_match
[       OK ] GuesserTest.empty_string_match (0 ms)
[ RUN      ] GuesserTest.single_space_string_not_match
[       OK ] GuesserTest.single_space_string_not_match (0 ms)
[ RUN      ] GuesserTest.perfect_alphabet_lowercase_character_match
[       OK ] GuesserTest.perfect_alphabet_lowercase_character_match (0 ms)
[ RUN      ] GuesserTest.perfect_alphabet_mixedcase_character_match
[       OK ] GuesserTest.perfect_alphabet_mixedcase_character_match (0 ms)
[ RUN      ] GuesserTest.perfect_mixed_character_match
[       OK ] GuesserTest.perfect_mixed_character_match (0 ms)
[ RUN      ] GuesserTest.perfect_alphabet_lowercase_character_not_match
[       OK ] GuesserTest.perfect_alphabet_lowercase_character_not_match (0 ms)
[ RUN      ] GuesserTest.perfect_alphabet_mixedcase_character_not_match
[       OK ] GuesserTest.perfect_alphabet_mixedcase_character_not_match (0 ms)
[ RUN      ] GuesserTest.perfect_mixed_character_not_match
[       OK ] GuesserTest.perfect_mixed_character_not_match (0 ms)
[ RUN      ] GuesserTest.char_32_not_match
[       OK ] GuesserTest.char_32_not_match (0 ms)
[ RUN      ] GuesserTest.char_32_match
[       OK ] GuesserTest.char_32_match (0 ms)
[ RUN      ] GuesserTest.initial_guess_remaining
[       OK ] GuesserTest.initial_guess_remaining (0 ms)
[ RUN      ] GuesserTest.guessed_once_remaining
[       OK ] GuesserTest.guessed_once_remaining (0 ms)
[ RUN      ] GuesserTest.guessed_twice_remaining
[       OK ] GuesserTest.guessed_twice_remaining (0 ms)
[ RUN      ] GuesserTest.guessed_thrice_remaining
[       OK ] GuesserTest.guessed_thrice_remaining (0 ms)
[ RUN      ] GuesserTest.guessed_once_locked_remaining
[       OK ] GuesserTest.guessed_once_locked_remaining (0 ms)
[ RUN      ] GuesserTest.guessed_twice_locked_remaining
[       OK ] GuesserTest.guessed_twice_locked_remaining (0 ms)
[ RUN      ] GuesserTest.guessed_thrice_locked_remaining
[       OK ] GuesserTest.guessed_thrice_locked_remaining (0 ms)
[ RUN      ] GuesserTest.guessed_once_set_remaining_to_initial
[       OK ] GuesserTest.guessed_once_set_remaining_to_initial (0 ms)
[ RUN      ] GuesserTest.guessed_twice_set_remaining_to_initial
[       OK ] GuesserTest.guessed_twice_set_remaining_to_initial (0 ms)
[ RUN      ] GuesserTest.guessed_thrice_set_remaining_to_initial
[       OK ] GuesserTest.guessed_thrice_set_remaining_to_initial (0 ms)
[ RUN      ] GuesserTest.distance_zero
[       OK ] GuesserTest.distance_zero (0 ms)
[ RUN      ] GuesserTest.distance_one_space
[       OK ] GuesserTest.distance_one_space (0 ms)
[ RUN      ] GuesserTest.distance_two_uppercase_space
[       OK ] GuesserTest.distance_two_uppercase_space (0 ms)
[ RUN      ] GuesserTest.distance_secret_size_maximum
[       OK ] GuesserTest.distance_secret_size_maximum (0 ms)
[ RUN      ] GuesserTest.distance_secret_size_maximum_reverse
[       OK ] GuesserTest.distance_secret_size_maximum_reverse (0 ms)
[ RUN      ] GuesserTest.Distance_EqualLength
[       OK ] GuesserTest.Distance_EqualLength (0 ms)
[ RUN      ] GuesserTest.Distance_ShorterGuess
[       OK ] GuesserTest.Distance_ShorterGuess (0 ms)
[ RUN      ] GuesserTest.distance_locked
[       OK ] GuesserTest.distance_locked (0 ms)
[ RUN      ] GuesserTest.distance_locked_zero
[       OK ] GuesserTest.distance_locked_zero (0 ms)
[ RUN      ] GuesserTest.distance_test
[       OK ] GuesserTest.distance_test (0 ms)
[----------] 30 tests from GuesserTest (1 ms total)

[----------] Global test environment tear-down
[==========] 30 tests from 1 test suite ran. (2 ms total)
[  PASSED  ] 30 tests.
File 'Guesser.cpp'
Lines executed:100.00% of 32
Branches executed:100.00% of 28
Taken at least once:89.29% of 28
Calls executed:90.91% of 22
Creating 'Guesser.cpp.gcov'

Lines executed:100.00% of 32


```

### CODE REVIEW

**Comment by kbuffardi** [comment]
No PR needed.

**Comment by sunami09** [comment]
@kbuffardi I was trying merge it to main-branch

**Comment by kbuffardi** [comment]
@sunami09 then just make sure you merge to your fork, not the ChicoState/Guesser repo

**Comment by sunami09** [comment]
@kbuffardi oh my mistake I didn't notice that. Thanks

**Pull request closed without merging**
